-- módulo 03: mudando a apresentação dos dados de uma consulta
-- evoluindo nos diferentes tipos de comando de seleção SQL

--aula 01: cláusula DISTINCT no comando SELECT
-- consegue ver as características comportamentais dos dados

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MACA';

SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;

--aula 02: limitando a saída da consulta
-- comando TOP mostra os primeiros registros serve pra ter uma amostra do dado que a gente tem
--limitador de saída

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MACA';

--qual é o comando SQL para listar as 10 primeiras vendas do dia 01/10/2017?
SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017-10-01';

--aula 03: ordenando a saída
--ORDER BY <LISTA DE CAMPOS> (ASC, DESC)
--quando omitimos o sentido da ordenação automaticamente ele vai ser ASC

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA ASC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

--qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limão" em quantidade

SELECT CODIGO_DO_PRODUTO FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

SELECT TOP 1 * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC

--aula 04:agrupando linhas das tabelas
--GROUP BY
--para usar GROUP BY é necessário que haja na seleção de campos pelo menos um campo onde é aplicado uma função de agregação
--funções de agregação contidas no SQL: SUM/AVG/MAX/MIN
--Junto ao comando GROUP BY só entra os campos que são critérios de junção e não o campo que tá sofrendo a função agregada
--GROUP BY é muito importante para criar relatórios, pra fazer sumarizações de dados, relatórios gerenciais

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

SELECT CIDADE, AVG(IDADE) AS [MÉDIA DE IDADE DOS CLIENTES] FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT CIDADE, AVG(IDADE) AS [MÉDIA DE IDADE DOS CLIENTES], SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

--não tem nenhum problema usar o nome do alias igual o da coluna
SELECT CIDADE, SUM(IDADE) AS IDADE, SUM(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

--COUNT(*) está contando o numero de linhas que estão sendo agrupadas usando o critério definido
SELECT CIDADE, COUNT(*) AS [NUMERO DE CLIENTES] FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) AS [QUANTIDADE DE PRODUTOS] FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS [QUANTIDADE DE PRODUTOS] FROM TABELA_DE_PRODUTOS WHERE SABOR = 'LARANJA' GROUP BY EMBALAGEM;

--Cada item da nota fiscal representa 1 venda de um determinado produto. Vimos no exercício
--anterior que temos várias vendas com quantidade igual a 99 litros para o produto '1101035'.
--Pergunto: quantas vendas foram feitas com quantidade igual a 99 litros para o produto '1101035'?

SELECT CODIGO_DO_PRODUTO, COUNT(*) AS [TOTAL DE VENDAS] FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99 GROUP BY CODIGO_DO_PRODUTO;
SELECT COUNT(*) AS [TOTAL DE VENDAS] FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

--aula 05: HAVING para filtrar campos agregados
--HAVING <FILTRO ENVOLVENDO AGREGAÇÃO>
--No filtro where eu não posso usar campos com funções de agregação

SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES 
GROUP BY ESTADO;

--An aggregate may not appear in the WHERE clause unless it is in a subquery contained in a HAVING clause or a select list, and the column being aggregated is an outer reference.
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES 
WHERE SUM(LIMITE_DE_CREDITO) >= 900000
GROUP BY ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES 
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >=10
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >=10
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS
WHERE PRECO_DE_LISTA >=10
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >= 20;

--verifique as quantidades totais de venda de cada produto e ordene do maior para o menor
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS [QUANTIDADE TOTAL DE VENDA]
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
ORDER BY SUM(QUANTIDADE) DESC;

--agora liste somente os produtos que venderam mais de 394000 unidades
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS [QUANTIDADE TOTAL DE VENDA]
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE) DESC;

--aula 06: classificando os campos
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA 
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA';

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'MANGA'
ORDER BY CLASSIFICACAO;

--ORDER BY ACEITA O ALIAS
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO;

--GROUP BY NÃO ACEITA O ALIAS PRECISA COLOCAR O CASE
SELECT
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO, COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END);

--Para cada cliente temos seus limites de crédito mensais. Liste somente o nome dos clientes e 
--os classifique por:
--Acima ou igual a 150000 - clientes grandes
--Entre 150000 E 110000 - clientes médios
--Menores que 110000 - clientes pequenos

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	  ELSE 'CLIENTE PEQUENO' END) AS [TIPO DE CLIENTE]
FROM TABELA_DE_CLIENTES;

SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	  ELSE 'CLIENTE PEQUENO' END) AS [TIPO DE CLIENTE]
FROM TABELA_DE_CLIENTES
ORDER BY [TIPO DE CLIENTE];

SELECT
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	  ELSE 'CLIENTE PEQUENO' END) AS [TIPO DE CLIENTE], COUNT(*) AS [TOTAL DE CLIENTES]
FROM TABELA_DE_CLIENTES
GROUP BY (CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
	  ELSE 'CLIENTE PEQUENO' END)









